# location & number
charger_list:
  west_gate:
    - - '南侧-1'
      - 'XYcjSf9nqvK612'
    - - '南侧-2'
      - 'XY31g0OtIZA711'
    - - '南侧-3'
      - 'XYV5mv5tnKHV9'
  east_gate:
    - - '北侧-1'
      - 'XYvlqZM8oCmT19' # fault
    - - '北侧-2'
      - 'XYnfw8BeyiXS16'
    - - '北侧-3'
      - 'XYEogTrLdXZx14'
    - - '北侧-4'
      - 'XYxN6z9ZETBZ17'
    - - '北侧-5'
      - 'XYBGw4c88NWd21'

# use this header to fake a visit by android mobile
headers:
  Host: 'mapi.7mate.cn'
  Connection: 'keep-alive'
  accept: 'application/vnd.ws.v1+json'
  User-Agent: 'Mozilla/5.0 (Linux; Android 7.1.2; MI 9 Build/N2G48C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.198 Mobile Safari/537.36 MicroMessenger/8.0.2.1860(0x28000234) Process/appbrand2 WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32 MiniProgramEnv/android'
  charset: 'utf-8'
  Accept-Encoding: 'gzip,compress,br,deflate'
  content-type: 'application/json'
  Referer: 'https://servicewechat.com/wx26caa1e6b60d4ef5/32/page-frame.html'

# I find it unnecessary to use real openid and phone!
openid: '01'
phone: '01'

# maybe useful someday...
appid: 'wx26caa1e6b60d4ef5'

en2zh:
  'east_gate': '东门'
  'west_gate': '西门'
  'south_gate': '南门'
  'north_gate': '北门'
