config_file_version = "20231008"

[system]
display_version = "4.2.1f"

[cache]
cache_mode = 1
# 0:Realtime, 
# 1:Passive Cache (User Request), 
# 2:Active Cache  (Cron Refresh, **Unimplemented feature**)

# Works when cache_mode == 1
refresh_time = 1.3

# Works when cache_mode == 2, sometimes works when cache_mode == 1
survival_time = 2 # minute
refuse_time = 3   # minute

[conditions]
enough_sum_num = 100    # 小于这个数提示紧张
enough_socket_num = 2.5 # 每个充电桩低于这个数字提示紧张

[stations."东门北侧"]
"N1" = "东门北侧 XYr6DGKCsRDZ5号设备"
"N2" = "东门北侧 XYnWrKKm2uY74号设备"
"N3" = "东门北侧 XYUOSoePDWDt1号设备"
"N4" = "东门北侧 XYbRBoaA2YMA3号设备"
"A" = "XYlFl6DnfgZH3"
"B" = "XY1eANYJoWM620"
"C" = "东门北侧 XYvIqZM8oCmT19号设备"
"D" = "东门北侧 XYnfw8BeyiXS16号设备"
"E" = "东门北侧 XYEogTrLdXZx14号设备"
"F" = "东门北侧 XYxN6z9ZETBZ17号设备"
"G" = "东门北侧 XYBGw4c88NWd21号设备"

[stations."东门南侧"]
"A" = "XYSfeYzOvLwN5"
"B" = "XYDSUGrzkRfX6"

[stations."西门北侧"]
"A" = "XYS2hOWumHDa13"
"B" = "XYp5iHwheZvf18"
"C" = "XY9HNPbegRgV15"

[stations."西门南侧"]
"A" = "XYcjSf9nqvK612"
"B" = "XY31g0OtIZA711"
"C" = "XYV5mv5tnKHV9"

[stations."南门西侧"]
"A" = "XY679RB8P35Y10"
"B" = "XYOGaVYy7OHu7"

[stations."南门东侧"]
"A" = "南门外东侧 XY5dXpywawqy6号设备"
"B" = "南门外东侧 XYsjnxW1MolG2号设备"

[stations."北门东北侧"]
"A" = "XYeo2IsT1Sx61"
"B" = "XYKCwwkZXBW62"
"C" = "XYTbok829tYo8"
"D" = "XYo7UstSCeu64"

[stations."北门东南侧"]
"A" = "北门东侧 XYbwFHY40PZK3号设备"
"B" = "北门东侧 XYgbwesjiMEy6号设备"
"C" = "北门东侧 XYnT1V47gbvQ5号设备"
"D" = "北门东侧 XYwgYSUv41Ve2号设备"
"E" = "北门东侧 XYG9NcgUXBlg4号设备"
"F" = "北门东侧 XYWOjzU06jWc1号设备"
