config_file_version = "20231023"

[system]
display_version = "4.2.3f"

[cache]
cache_mode = 1
# 0:Realtime, 
# 1:Passive Cache (User Request), 
# 2:Active Cache  (Cron Refresh, **Unimplemented feature**)

# Works when cache_mode == 1
refresh_time = 1.3

# Works when cache_mode == 2, sometimes works when cache_mode == 1
survival_time = 2 # minute
refuse_time = 3   # minute

[conditions]
enough_sum_num = 100    # 小于这个数提示紧张
enough_socket_num = 2.5 # 每个充电桩低于这个数字提示紧张

[stations."东门北侧"]
"A" = "XYBGw4c88NWd21"
"B" = "XYxN6z9ZETBZ17"
"C" = "XYEogTrLdXZx14"
"D" = "XYnfw8BeyiXS16"
"E" = "XYvIqZM8oCmT19"
"F" = "XY1eANYJoWM620"
"G" = "XYlFl6DnfgZH3"
"H" = "XYbRBoaA2YMA3"
"I" = "XYUOSoePDWDt1"
"J" = "XYnWrKKm2uY74"
"K" = "XYr6DGKCsRDZ5"

[stations."东门南侧"]
"A" = "XYSfeYzOvLwN5"
"B" = "XYDSUGrzkRfX6"

[stations."西门北侧"]
"A" = "XYS2hOWumHDa13"
"B" = "XYp5iHwheZvf18"
"C" = "XY9HNPbegRgV15"

[stations."西门南侧"]
"A" = "XYcjSf9nqvK612"
"B" = "XY31g0OtIZA711"
"C" = "XYV5mv5tnKHV9"

[stations."南门西侧"]
"A" = "XY679RB8P35Y10"
"B" = "!XYOGaVYy7OHu7" # 充电桩坏了，所以故意加了一个`!`

[stations."南门东侧"]
"A" = "XY5dXpywawqy6"
"B" = "XYsjnxW1MolG2"

[stations."北门东北侧"]
"A" = "XYeo2IsT1Sx61"
"B" = "XYKCwwkZXBW62"
"C" = "XYTbok829tYo8"
"D" = "XYo7UstSCeu64"

[stations."北门东南侧"]
"A" = "XYbwFHY40PZK3"
"B" = "XYgbwesjiMEy6"
"C" = "XYnT1V47gbvQ5"
"D" = "XYwgYSUv41Ve2"
"E" = "XYG9NcgUXBlg4"
"F" = "XYWOjzU06jWc1"

[stations."橘园北侧南"]
"A" = "XYZqtFOCjoo024"
"B" = "XYe44rfj1m7h16"
"C" = "XYT9bmaPxipL7"
"D" = "XY4xIzFgzaPz8"
"E" = "XYNoaWAuLzwl22"
"F" = "XY2yFr4CwQNr9"
"G" = "XYNfAveZc37610"
"H" = "XYDBo8fgABjB3"
"I" = "XYn03Mm9IvOy1"
"J" = "XYnA1fapkKoJ23"

[stations."校医院西"]
"A" = "XYhsT6K7WuFF2"
"B" = "XYSrI29yuVPy4"
"C" = "XYmX1k57YPHa18"
"D" = "XYL81WkCxNTu17"
"E" = "XYI1OP4t44eM5"
"F" = "XYgfTM8RL9mE6"
"G" = "XYyyylX0CqbR12"
"H" = "XYKnEbnnJCeb11"
"I" = "XYQ9V3oRnl7T14"
