import os
import tomllib
import json

"""
    预处理，用于生成 auto_gen/config.js

    需要 Python >= 3.11 运行
"""

path: str = os.path.abspath(os.path.dirname(__file__))
output = {}

if __name__ == "__main__":
    with open(
        os.path.join(path, "config.toml"),
        "rb",
    ) as config_toml_file:
        config = tomllib.load(config_toml_file)
        config["stations_r"] = {}
        config["stations_chargers_num"] = {}
        config["status_detail_template"] = {}

        for station in config["stations"]:
            config["status_detail_template"][station] = {}
            config["stations_chargers_num"][station] = 0
            for charger, charger_no in config["stations"][station].items():
                config["status_detail_template"][station][charger] = None
                config["stations_r"][charger_no] = {
                    "station": station,
                    "charger_friendly_no": charger,
                }
                config["stations_chargers_num"][station] += 1

        if not os.path.exists(os.path.join(path, "auto_gen")):
            os.makedirs(os.path.join(path, "auto_gen"))

        with open(
            os.path.join(path, "auto_gen", "config.js"), "w", encoding="utf-8"
        ) as config_js:
            config_js.write("// DO NOT EDIT THIS FILE!!!\n\n")
            config_js.write(f"const CONFIG = JSON.parse('{json.dumps(config)}');\n\n")
            config_js.write("export default CONFIG;")
