// DO NOT EDIT THIS FILE!!!

const CONFIG = {
  "config_file_version": "20240421",
  "system": {"display_version": "4.2.5f"},
  "tip": {"enable": false},
  "cache": {"cache_mode": 1, "refresh_time": 1.3, "survival_time": 2, "refuse_time": 3},
  "conditions": {"enough_sum_num": 100, "enough_socket_num": 2.5},
  "stations": {
    "\u4e1c\u95e8\u5317\u4fa7": {
        A: "XYBGw4c88NWd21",
        B: "XYxN6z9ZETBZ17",
        C: "XYEogTrLdXZx14",
        D: "XYnfw8BeyiXS16",
        E: "XYvIqZM8oCmT19",
        F: "XY1eANYJoWM620",
        G: "XYlFl6DnfgZH3",
        H: "XYbRBoaA2YMA3",
        I: "XYUOSoePDWDt1",
        J: "XYnWrKKm2uY74",
        K: "XYr6DGKCsRDZ5",
    },
    "\u4e1c\u95e8\u5357\u4fa7": { A: "XYSfeYzOvLwN5", B: "XYDSUGrzkRfX6" },
    "\u897f\u95e8\u5317\u4fa7": {
        A: "XYS2hOWumHDa13",
        B: "XYp5iHwheZvf18",
        C: "XY9HNPbegRgV15",
    },
    "\u897f\u95e8\u5357\u4fa7": {
        A: "XYcjSf9nqvK612",
        B: "XY31g0OtIZA711",
        C: "XYV5mv5tnKHV9",
    },
    "\u5357\u95e8\u897f\u4fa7": { A: "XY679RB8P35Y10", B: "XYOGaVYy7OHu7" },
    "\u5357\u95e8\u4e1c\u4fa7": { A: "XY5dXpywawqy6", B: "XYsjnxW1MolG2" },
    "\u5317\u95e8\u4e1c\u5317\u4fa7": {
        A: "XYeo2IsT1Sx61",
        B: "XYKCwwkZXBW62",
        C: "XYTbok829tYo8",
        D: "XYo7UstSCeu64",
    },
    "\u5317\u95e8\u4e1c\u5357\u4fa7": {
        A: "XYbwFHY40PZK3",
        B: "XYgbwesjiMEy6",
        C: "XYnT1V47gbvQ5",
        D: "XYwgYSUv41Ve2",
        E: "XYG9NcgUXBlg4",
        F: "XYWOjzU06jWc1",
    },
    "\u6a58\u56ed\u5317\u4fa7\u5357": {
        A: "XYZqtFOCjoo024",
        B: "XYe44rfj1m7h16",
        C: "XYT9bmaPxipL7",
        D: "XY4xIzFgzaPz8",
        E: "XYNoaWAuLzwl22",
        F: "XY2yFr4CwQNr9",
        G: "XYNfAveZc37610",
        H: "XYDBo8fgABjB3",
        I: "XYn03Mm9IvOy1",
        J: "XYnA1fapkKoJ23",
    },
    "\u6821\u533b\u9662\u897f": {
        A: "XYQ9V3oRnl7T14",
        B: "XYKnEbnnJCeb11",
        C: "XYyyylX0CqbR12",
        D: "XYgfTM8RL9mE6",
        E: "XYI1OP4t44eM5",
        F: "XYL81WkCxNTu17",
        G: "XYmX1k57YPHa18",
        H: "XYSrI29yuVPy4",
        I: "XYhsT6K7WuFF2",
    },
},
stations_r: {
    XYBGw4c88NWd21: {
        station: "\u4e1c\u95e8\u5317\u4fa7",
        charger_friendly_no: "A",
    },
    XYxN6z9ZETBZ17: {
        station: "\u4e1c\u95e8\u5317\u4fa7",
        charger_friendly_no: "B",
    },
    XYEogTrLdXZx14: {
        station: "\u4e1c\u95e8\u5317\u4fa7",
        charger_friendly_no: "C",
    },
    XYnfw8BeyiXS16: {
        station: "\u4e1c\u95e8\u5317\u4fa7",
        charger_friendly_no: "D",
    },
    XYvIqZM8oCmT19: {
        station: "\u4e1c\u95e8\u5317\u4fa7",
        charger_friendly_no: "E",
    },
    XY1eANYJoWM620: {
        station: "\u4e1c\u95e8\u5317\u4fa7",
        charger_friendly_no: "F",
    },
    XYlFl6DnfgZH3: {
        station: "\u4e1c\u95e8\u5317\u4fa7",
        charger_friendly_no: "G",
    },
    XYbRBoaA2YMA3: {
        station: "\u4e1c\u95e8\u5317\u4fa7",
        charger_friendly_no: "H",
    },
    XYUOSoePDWDt1: {
        station: "\u4e1c\u95e8\u5317\u4fa7",
        charger_friendly_no: "I",
    },
    XYnWrKKm2uY74: {
        station: "\u4e1c\u95e8\u5317\u4fa7",
        charger_friendly_no: "J",
    },
    XYr6DGKCsRDZ5: {
        station: "\u4e1c\u95e8\u5317\u4fa7",
        charger_friendly_no: "K",
    },
    XYSfeYzOvLwN5: {
        station: "\u4e1c\u95e8\u5357\u4fa7",
        charger_friendly_no: "A",
    },
    XYDSUGrzkRfX6: {
        station: "\u4e1c\u95e8\u5357\u4fa7",
        charger_friendly_no: "B",
    },
    XYS2hOWumHDa13: {
        station: "\u897f\u95e8\u5317\u4fa7",
        charger_friendly_no: "A",
    },
    XYp5iHwheZvf18: {
        station: "\u897f\u95e8\u5317\u4fa7",
        charger_friendly_no: "B",
    },
    XY9HNPbegRgV15: {
        station: "\u897f\u95e8\u5317\u4fa7",
        charger_friendly_no: "C",
    },
    XYcjSf9nqvK612: {
        station: "\u897f\u95e8\u5357\u4fa7",
        charger_friendly_no: "A",
    },
    XY31g0OtIZA711: {
        station: "\u897f\u95e8\u5357\u4fa7",
        charger_friendly_no: "B",
    },
    XYV5mv5tnKHV9: {
        station: "\u897f\u95e8\u5357\u4fa7",
        charger_friendly_no: "C",
    },
    XY679RB8P35Y10: {
        station: "\u5357\u95e8\u897f\u4fa7",
        charger_friendly_no: "A",
    },
    XYOGaVYy7OHu7: {
        station: "\u5357\u95e8\u897f\u4fa7",
        charger_friendly_no: "B",
    },
    XY5dXpywawqy6: {
        station: "\u5357\u95e8\u4e1c\u4fa7",
        charger_friendly_no: "A",
    },
    XYsjnxW1MolG2: {
        station: "\u5357\u95e8\u4e1c\u4fa7",
        charger_friendly_no: "B",
    },
    XYeo2IsT1Sx61: {
        station: "\u5317\u95e8\u4e1c\u5317\u4fa7",
        charger_friendly_no: "A",
    },
    XYKCwwkZXBW62: {
        station: "\u5317\u95e8\u4e1c\u5317\u4fa7",
        charger_friendly_no: "B",
    },
    XYTbok829tYo8: {
        station: "\u5317\u95e8\u4e1c\u5317\u4fa7",
        charger_friendly_no: "C",
    },
    XYo7UstSCeu64: {
        station: "\u5317\u95e8\u4e1c\u5317\u4fa7",
        charger_friendly_no: "D",
    },
    XYbwFHY40PZK3: {
        station: "\u5317\u95e8\u4e1c\u5357\u4fa7",
        charger_friendly_no: "A",
    },
    XYgbwesjiMEy6: {
        station: "\u5317\u95e8\u4e1c\u5357\u4fa7",
        charger_friendly_no: "B",
    },
    XYnT1V47gbvQ5: {
        station: "\u5317\u95e8\u4e1c\u5357\u4fa7",
        charger_friendly_no: "C",
    },
    XYwgYSUv41Ve2: {
        station: "\u5317\u95e8\u4e1c\u5357\u4fa7",
        charger_friendly_no: "D",
    },
    XYG9NcgUXBlg4: {
        station: "\u5317\u95e8\u4e1c\u5357\u4fa7",
        charger_friendly_no: "E",
    },
    XYWOjzU06jWc1: {
        station: "\u5317\u95e8\u4e1c\u5357\u4fa7",
        charger_friendly_no: "F",
    },
    XYZqtFOCjoo024: {
        station: "\u6a58\u56ed\u5317\u4fa7\u5357",
        charger_friendly_no: "A",
    },
    XYe44rfj1m7h16: {
        station: "\u6a58\u56ed\u5317\u4fa7\u5357",
        charger_friendly_no: "B",
    },
    XYT9bmaPxipL7: {
        station: "\u6a58\u56ed\u5317\u4fa7\u5357",
        charger_friendly_no: "C",
    },
    XY4xIzFgzaPz8: {
        station: "\u6a58\u56ed\u5317\u4fa7\u5357",
        charger_friendly_no: "D",
    },
    XYNoaWAuLzwl22: {
        station: "\u6a58\u56ed\u5317\u4fa7\u5357",
        charger_friendly_no: "E",
    },
    XY2yFr4CwQNr9: {
        station: "\u6a58\u56ed\u5317\u4fa7\u5357",
        charger_friendly_no: "F",
    },
    XYNfAveZc37610: {
        station: "\u6a58\u56ed\u5317\u4fa7\u5357",
        charger_friendly_no: "G",
    },
    XYDBo8fgABjB3: {
        station: "\u6a58\u56ed\u5317\u4fa7\u5357",
        charger_friendly_no: "H",
    },
    XYn03Mm9IvOy1: {
        station: "\u6a58\u56ed\u5317\u4fa7\u5357",
        charger_friendly_no: "I",
    },
    XYnA1fapkKoJ23: {
        station: "\u6a58\u56ed\u5317\u4fa7\u5357",
        charger_friendly_no: "J",
    },
    XYQ9V3oRnl7T14: {
        station: "\u6821\u533b\u9662\u897f",
        charger_friendly_no: "A",
    },
    XYKnEbnnJCeb11: {
        station: "\u6821\u533b\u9662\u897f",
        charger_friendly_no: "B",
    },
    XYyyylX0CqbR12: {
        station: "\u6821\u533b\u9662\u897f",
        charger_friendly_no: "C",
    },
    XYgfTM8RL9mE6: {
        station: "\u6821\u533b\u9662\u897f",
        charger_friendly_no: "D",
    },
    XYI1OP4t44eM5: {
        station: "\u6821\u533b\u9662\u897f",
        charger_friendly_no: "E",
    },
    XYL81WkCxNTu17: {
        station: "\u6821\u533b\u9662\u897f",
        charger_friendly_no: "F",
    },
    XYmX1k57YPHa18: {
        station: "\u6821\u533b\u9662\u897f",
        charger_friendly_no: "G",
    },
    XYSrI29yuVPy4: {
        station: "\u6821\u533b\u9662\u897f",
        charger_friendly_no: "H",
    },
    XYhsT6K7WuFF2: {
        station: "\u6821\u533b\u9662\u897f",
        charger_friendly_no: "I",
    },
},
stations_chargers_num: {
    "\u4e1c\u95e8\u5317\u4fa7": 11,
    "\u4e1c\u95e8\u5357\u4fa7": 2,
    "\u897f\u95e8\u5317\u4fa7": 3,
    "\u897f\u95e8\u5357\u4fa7": 3,
    "\u5357\u95e8\u897f\u4fa7": 2,
    "\u5357\u95e8\u4e1c\u4fa7": 2,
    "\u5317\u95e8\u4e1c\u5317\u4fa7": 4,
    "\u5317\u95e8\u4e1c\u5357\u4fa7": 6,
    "\u6a58\u56ed\u5317\u4fa7\u5357": 10,
    "\u6821\u533b\u9662\u897f": 9,
},
status_detail_template: {
    "\u4e1c\u95e8\u5317\u4fa7": {
        A: null,
        B: null,
        C: null,
        D: null,
        E: null,
        F: null,
        G: null,
        H: null,
        I: null,
        J: null,
        K: null,
    },
    "\u4e1c\u95e8\u5357\u4fa7": { A: null, B: null },
    "\u897f\u95e8\u5317\u4fa7": { A: null, B: null, C: null },
    "\u897f\u95e8\u5357\u4fa7": { A: null, B: null, C: null },
    "\u5357\u95e8\u897f\u4fa7": { A: null, B: null },
    "\u5357\u95e8\u4e1c\u4fa7": { A: null, B: null },
    "\u5317\u95e8\u4e1c\u5317\u4fa7": {
        A: null,
        B: null,
        C: null,
        D: null,
    },
    "\u5317\u95e8\u4e1c\u5357\u4fa7": {
        A: null,
        B: null,
        C: null,
        D: null,
        E: null,
        F: null,
    },
    "\u6a58\u56ed\u5317\u4fa7\u5357": {
        A: null,
        B: null,
        C: null,
        D: null,
        E: null,
        F: null,
        G: null,
        H: null,
        I: null,
        J: null,
    },
    "\u6821\u533b\u9662\u897f": {
        A: null,
        B: null,
        C: null,
        D: null,
        E: null,
        F: null,
        G: null,
        H: null,
        I: null,
    },
  },
};
  
export default CONFIG;
  